### ISSUE TITLE
Macro hygiene for at-batch

### ISSUE THREAD

**Issue by ranocha** [JuliaSIMD/CheapThreads.jl#11]
Thanks for this nice package! Since there is not really an official documentation, I'm probably a bit too early :wink: Aer reading your nice posts in https://discourse.julialang.org/t/threads-threads-with-one-thread-how-to-remove-the-overhead/58435, @chriselrod, I wanted to try CheapThreads.jl and got the following error.
```julia
julia> module MyModule

       using CheapThreads: @batch

       my_indices(a) = 1:size(a, 1)

       function foo!(dest, src)
           @batch for j in 1:size(src, 2)
               for i in my_indices(src)
                   dest[i,j] = exp(sin(cos(src[i,j])))
               end
           end
       end

       end


Main.MyModule

julia> a = randn(10^4); b = similar(a);

julia> MyModule.foo!(b, a)
ERROR: UndefVarError: my_indices not defined
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/CheapThreads/7uVAE/src/closure.jl:10 [inlined]
 [2] foo!(dest::Vector{Float64}, src::Vector{Float64})
   @ Main.MyModule ./REPL[1]:8
 [3] top-level scope
   @ REPL[3]:1
```
To me, it looks like an issue with macro hygiene.

**Comment by chriselrod** [comment]
Thanks for the issue!
You're right, I forgot to `esc` the functions.

Also, `@batch` only looks at the first loop, which in this case is `for j in 1:size(src, 2)`. `size(src,2) == 1`, meaning it'll be single threaded.

Aside from this of course being another example that'd see a big speed up from LoopVectorization's SIMD, it'd also thread the inner loop if the outer loop doesn't have enough iterations. LoopVectorization currently only supports using `1` or `N` indices though, where `N` is the dimensionality of the array.
Maybe I should just ignore all extra indices.

**Comment by chriselrod** [comment]
```julia
julia> a = rand(144,144); b = similar(a);

julia> using .MyModule: my_indices

julia> function foo_avxt!(dest, src)
           @avxt for j in 1:size(src, 2)
               for i in my_indices(src)
                   dest[i,j] = exp(sin(cos(src[i,j])))
               end
           end
       end
foo_avxt! (generic function with 1 method)

julia> function foo_threads!(dest, src)
           Threads.@threads for j in 1:size(src, 2)
               for i in my_indices(src)
                   dest[i,j] = exp(sin(cos(src[i,j])))
               end
           end
       end
foo_threads! (generic function with 1 method)

julia> @benchmark foo_threads!($b, $a)
BenchmarkTools.Trial:
  memory estimate:  16.12 KiB
  allocs estimate:  181
  --------------
  minimum time:     79.030 μs (0.00% GC)
  median time:      87.382 μs (0.00% GC)
  mean time:        92.765 μs (1.10% GC)
  maximum time:     3.697 ms (95.89% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark MyModule.foo!($b, $a)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     19.860 μs (0.00% GC)
  median time:      20.633 μs (0.00% GC)
  mean time:        20.726 μs (0.00% GC)
  maximum time:     138.916 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark foo_avxt!($b, $a)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     4.244 μs (0.00% GC)
  median time:      4.550 μs (0.00% GC)
  mean time:        4.561 μs (0.00% GC)
  maximum time:     13.517 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     7
```

**Comment by ranocha** [comment]
Thanks for this quick fix, @chriselrod - and of course for your great work in general :+1: 

Hijacking this issue a bit: You're right, the example code should use LoopVectorization if used in production. I just cooked up this example as an MWE. The [actual code](https://github.com/trixi-framework/Trixi.jl/blob/a00283eb36c08bdd717ae9424f8199cbe76df627/src/solvers/dg/dg_2d.jl#L161-L186) looks more like this
```julia
function calc_volume_integral!(du::AbstractArray{<:Any,4}, u,
                               nonconservative_terms::Val{false}, equations,
                               volume_integral::VolumeIntegralWeakForm,
                               dg::DGSEM, cache)
  @unpack derivative_dhat = dg.basis

  @threaded for element in eachelement(dg, cache)
    for j in eachnode(dg), i in eachnode(dg)
      u_node = get_node_vars(u, equations, dg, i, j, element)

      flux1 = flux(u_node, 1, equations)
      for ii in eachnode(dg)
        integral_contribution = derivative_dhat[ii, i] * flux1
        add_to_node_vars!(du, integral_contribution, equations, dg, ii, j, element)
      end

      flux2 = flux(u_node, 2, equations)
      for jj in eachnode(dg)
        integral_contribution = derivative_dhat[jj, j] * flux2
        add_to_node_vars!(du, integral_contribution, equations, dg, i, jj, element)
      end
    end
  end

  return nothing
end
```
where I wanted to replace `@threaded` by `@batch`. I wrote a special case of this function avoiding the general convenience functions `get_node_vars`, `flux` etc. in https://github.com/trixi-framework/Trixi.jl/pull/429 for one special choice of `equations`. In our hyperbolic PDE solver [Trixi.jl](https://github.com/trixi-framework/Trixi.jl), we use `u_node::SVector` internally to make the implementation of our code simple (and relatively efficient compared to similar Fortran codes out there). However, we miss the opportunity to use SIMD and your great work on LoopVectorization in this way. Would you have a suggestion how we could use an abstract implementation like the one above with LoopVectorization.jl?

**Comment by chriselrod** [comment]
Clicking that PR, it looks like you're already using `@avx` in those special cases.
But, it isn't possible to do that in general. The code in LoopVectorization itself, for example, isn't SIMD.

I think it'd be possible one day to SIMD a much more complex programs [a la ISPC](https://pharr.org/matt/blog/2018/04/18/ispc-origins.html), but even then lots of code wouldn't be practical.

If you want to know if a function is currently compatible, you could try calling it with `VectorizationBase.Vec`s in place of scalars.
Branches will be the biggest obstacle.

**Comment by ranocha** [comment]
Okay, thanks for the info!
