### ISSUE TITLE
Allocations in at-batch

### ISSUE THREAD

**Issue by ranocha** [JuliaSIMD/CheapThreads.jl#19]
Here is an MWE  based on https://github.com/trixi-framework/Trixi.jl/pull/509 where `@batch` creates additional allocations.

```julia
julia> using Pkg; Pkg.status("CheapThreads")
      Status `/tmp/jl_2FEv89/Project.toml`
  [b630d9fa] CheapThreads v0.2.0

julia> Threads.nthreads()
2

julia> using CheapThreads

julia> function foo!(dest, cache)
           @batch for i in eachindex(dest)
               factor = -cache.a[i]
               dest[i] *= factor
           end
       end
foo! (generic function with 1 method)

julia> dest = ones(20); cache = (; a = ones(length(dest)));

julia> foo!(dest, cache) # compile the method

julia> @allocated foo!(dest, cache)
16
```
While these are only very few allocations, more can occur in more complex examples from https://github.com/trixi-framework/Trixi.jl/pull/509.

**Comment by chriselrod** [comment]
Ah, passing in structs with with at least 1 non-isbits field will allocate in general.
I added special handling for `Tuple`s, and now added special handling for `NamedTuple`s, so these at least shouldn't allocate anymore.

I also added a `minbatch` keyword argument option.
```julia
function foo!(dest, cache)
    @batch minbatch=200 for i in eachindex(dest)
        factor = -cache.a[i]
        dest[i] *= factor
    end
end
```
Setting `200` for example means that it will use at most `max(1, length(dest) ÷ 200)` threads.

**Comment by ranocha** [comment]
Thanks a lot, that sounds really good :+1: This specific example doesn't allocate anymore using CheapThreads v0.2.1.

> Of course, if it is a loop that LoopVectorization understands, `@avxt` will do the cost evaluation and set the threshold for you.

Yeah, I'm re-writing loops where `@avxt` can be applied successfully. However, the example above was mainly an MWE.

**Comment by sloede** [comment]
Just for reference (mostly for myself): If I change the example above such that `cache` in `foo!` is actually a struct with field `a`, it does allocate again, but will then not allocate if I first unpack `a`. So it really is about how data is used specifically. I just thought this might be good to keep in mind if we want to avoid this performance issue in Trixi.

Using a `struct` instead of a `NamedTuple` allocates (with `CheapThreads@v0.2.1`) in `foo!`, but does not in `bar!`:
```julia
julia> using Pkg; Pkg.status("CheapThreads")
      Status `/mnt/ssd/home/mschlott/.julia/environments/v1.6/Project.toml`
  [b630d9fa] CheapThreads v0.2.1

julia> Threads.nthreads()
2

julia> using CheapThreads

julia> function foo!(dest, cache)
           @batch for i in eachindex(dest)
               factor = -cache.a[i]
               dest[i] *= factor
           end
       end
foo! (generic function with 1 method)

julia> function bar!(dest, cache)
           a = cache.a
           @batch for i in eachindex(dest)
               factor = -a[i]
               dest[i] *= factor
           end
       end
bar! (generic function with 1 method)

julia> struct Cache
         a::Vector{Float64}
       end

julia> dest = ones(20); cache = Cache(ones(length(dest)));

julia> foo!(dest, cache) # compile the method

julia> @allocated foo!(dest, cache)
16

julia> bar!(dest, cache) # compile the method

julia> @allocated bar!(dest, cache)
0
```
